services:
  neo4j:
    image: neo4j:latest
    container_name: neo4jLabbi
    environment:
      - NEO4J_AUTH=neo4j/latuerts
    ports:
      - "7474:7474"   # HTTP browser
      - "7687:7687"   # Bolt (Go access)
    volumes:
      - neo4j_data:/data
    networks:
      - labbi-net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labbi-web
    expose:
      - "8080"  # <-- expose statt ports, da Reverse Proxy übernimmt
    depends_on:
      - neo4j
    networks:
      - labbi-net
    env_file:
      - .env
    environment:
      NEO4J_URI: bolt://neo4j:7687
      SERVER_ADDRESS: "0.0.0.0:8080"

  nginx:
    image: nginx:latest
    container_name: labbi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./internal/public:/var/www/html
      - ./static:/var/www/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - labbi-net

volumes:
  neo4j_data:

networks:
  labbi-net:
    driver: bridge

